# Generated by Django 3.0.5 on 2021-01-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
